steps:
# Build trainer image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west3-docker.pkg.dev/mlops-fakenews/mlops-fakenews-container/trainer:latest',
    '-f',
    './trainer.dockerfile'
  ]
  secretEnv:
    - 'SERVICE_ACCOUNT_CREDENTIALS'
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west3-docker.pkg.dev/mlops-fakenews/mlops-fakenews-container/trainer:latest'
  ]
# Build predictor image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image predictor'
  args: [
    'build',
    '.',
    '-t',
    'europe-west3-docker.pkg.dev/mlops-fakenews/mlops-fakenews-container/predict:latest',
    '-f',
    './predict.dockerfile'
  ]
  secretEnv:
    - 'SERVICE_ACCOUNT_CREDENTIALS'
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image predictor'
  args: [
    'push',
    'europe-west3-docker.pkg.dev/mlops-fakenews/mlops-fakenews-container/predict:latest'
  ]
- name: python:3.11-slim
  entrypoint: python
  args: ['fakenews/model/train_model.py']
  secretEnv:
    - 'WANDB_API_KEY'
    - 'WANDB_PROJECT'
    - 'WANDB_ENTITY'
availableSecrets:
  secretManager:
  - versionName: 'projects/mlops-fakenews/secrets/WANDB_API_KEY/versions/latest'
    env: 'WANDB_API_KEY'
  - versionName: 'projects/mlops-fakenews/secrets/WANDB_PROJECT/versions/latest'
    env: 'WANDB_PROJECT'
  - versionName: 'projects/mlops-fakenews/secrets/WANDB_ENTITY/versions/latest'
    env: 'WANDB_ENTITY'
  - versionName: 'projects/mlops-fakenews/secrets/SERVICE_ACCOUNT_CREDENTIALS/versions/latest'
    env: 'SERVICE_ACCOUNT_CREDENTIALS'
#logsBucket: 'gs://mlops-logs-bucket'
options:
  logging: CLOUD_LOGGING_ONLY




# This was a test to see if the cache was working
#- name: 'gcr.io/cloud-builders/docker'
#  id: 'Setup BuildKit'
#  entrypoint: 'bash'
#  args:
#  - '-c'
#  - |
#    export DOCKER_BUILDKIT=1
#    docker buildx create --use
#
#- name: 'gcr.io/cloud-builders/docker'
#  id: 'Build container image predictor'
#  args: [
#    'buildx',
#    'build',
#    '--progress=plain',
#    '--cache-from', 'type=local,src=/cache',
#    '--cache-to', 'type=local,dest=/cache',
#    '-t', 'europe-west3-docker.pkg.dev/mlops-fakenews/mlops-fakenews-container/predict:latest',
#    '-f', './predict.dockerfile',
#    '.'
#  ]
#
#- name: 'gcr.io/cloud-builders/docker'
#  id: 'Push container image predictor'
#  args: [
#    'push',
#    'europe-west3-docker.pkg.dev/mlops-fakenews/mlops-fakenews-container/predict:latest'
#  ]
#
#options:
#  env:
#  - 'DOCKER_BUILDKIT=1'
