steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west3-docker.pkg.dev/mlops-fakenews/mlops-fakenews-container/train1',
    '-f',
    './trainer.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west3-docker.pkg.dev/mlops-fakenews/mlops-fakenews-container/train1'
  ]
