steps:
# Build trainer image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west3-docker.pkg.dev/mlops-fakenews/mlops-fakenews-container/trainer:latest',
    '-f',
    './trainer.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west3-docker.pkg.dev/mlops-fakenews/mlops-fakenews-container/trainer:latest'
  ]
# Build predictor image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image predictor'
  args: [
    'build',
    '.',
    '-t',
    'europe-west3-docker.pkg.dev/mlops-fakenews/mlops-fakenews-container/predict:latest',
    '-f',
    './predict.dockerfile'
  ]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image predictor'
  args: [
    'push',
    'europe-west3-docker.pkg.dev/mlops-fakenews/mlops-fakenews-container/predict:latest'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
  logsBucket: gs://mlops-fakenews_cloudbuild/logs/


# This was a test to see if the cache was working
#- name: 'gcr.io/cloud-builders/docker'
#  id: 'Setup BuildKit'
#  entrypoint: 'bash'
#  args:
#  - '-c'
#  - |
#    export DOCKER_BUILDKIT=1
#    docker buildx create --use
#
#- name: 'gcr.io/cloud-builders/docker'
#  id: 'Build container image predictor'
#  args: [
#    'buildx',
#    'build',
#    '--progress=plain',
#    '--cache-from', 'type=local,src=/cache',
#    '--cache-to', 'type=local,dest=/cache',
#    '-t', 'europe-west3-docker.pkg.dev/mlops-fakenews/mlops-fakenews-container/predict:latest',
#    '-f', './predict.dockerfile',
#    '.'
#  ]
#
#- name: 'gcr.io/cloud-builders/docker'
#  id: 'Push container image predictor'
#  args: [
#    'push',
#    'europe-west3-docker.pkg.dev/mlops-fakenews/mlops-fakenews-container/predict:latest'
#  ]
#
#options:
#  env:
#  - 'DOCKER_BUILDKIT=1'
