lr: 1e-5
batch_size: 32
epochs: 5
patience: 3
random_state: 2018
test_size: 0.3
val_size: 0.5
filename: 'model'
verbose: True
devices: 1
log_every_n_steps: 50
refresh_rate: 50
precision: "32"
profiler: "simple"
num_runs: 5
sweep: False
pruning: False
pruning_rate : 0.3
save_model: False
log_model: True
local_wandb: False
local_data: False
