steps:
# Build trainer image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image monitoring'
  args: [
    'build',
    '.',
    '-t',
    'europe-west3-docker.pkg.dev/mlops-fakenews/mlops-fakenews-container/monitoring:latest',
    '-f',
    './docker/monitoring.dockerfile'
  ]
  secretEnv:
    - 'SERVICE_ACCOUNT_CREDENTIALS'
# Push monitoring image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image monitoring'
  args: [
    'push',
    'europe-west3-docker.pkg.dev/mlops-fakenews/mlops-fakenews-container/monitoring:latest'
  ]
# Deploy to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run'
  args: [
    'run',
    'deploy',
    'monitoring',
    '--image',
    'europe-west3-docker.pkg.dev/mlops-fakenews/mlops-fakenews-container/monitoring:latest',
    '--region',
    'europe-west3',
    '--platform',
    'managed',
    '--allow-unauthenticated'
  ]
availableSecrets:
  secretManager:
  - versionName: 'projects/mlops-fakenews/secrets/SERVICE_ACCOUNT_CREDENTIALS/versions/latest'
    env: 'SERVICE_ACCOUNT_CREDENTIALS'
options:
  logging: CLOUD_LOGGING_ONLY
