program: fakenews/model/train_model.py
method: random
metric:
  goal: minimize
  name: val_loss
parameters:
  train.lr:
    values: [1e-5, 5e-5, 1e-4]
  train.batch_size:
    values: [16, 32, 64]
  train.pruning_rate:
    values: [0.1, 0.2, 0.3, 0.4]
  model.dropout_rate:
    values: [0.1, 0.2, 0.4]
