site_name: MLOps Fake News Classification
#
site_author: Tobias Brock, Stefanie Schwarz, Anne Gritto

theme:
  language: en
  name: material
  features:
  - content.code.copy
  - content.code.annotate
markdown_extensions:
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Setup: setup.md
  - DVC: dvc.md
  - Makefile: makefile.md
  - Model training: run_local.md
  - Inference: inference.md
  - Continuous Integration: ci.md
  - Docker: docker.md
  - Monitoring: monitoring.md
