temperature: 2.0
alpha: 0.5
st_model_name: "distilbert-base-uncased" #"bert-base-uncased"
st_hidden_size: 768  # Adjust based on the student model's hidden size
st_intermediate_size: 256  # Adjust as needed
