name: Code formatting
# Check whether code is formatted correctly with ruff
on:
  push:
    branches: [ main, pytests ]
  pull_request:
    branches: [ main, pytests ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip'
        cache-dependency-path: setup.py
    - name: Install dependencies
      run: |
        pip install ruff
        pip list
    - name: Ruff check
      run: ruff check .
    - name: Ruff format
      run: ruff format .