name: Docker Image Continuous Integration

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and push the trainer Docker image
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login \
          -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
        docker build . --file trainer.dockerfile \
          --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}-trainer:$GITHUB_SHA
        docker push \
          docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}-trainer:$GITHUB_SHA

    - name: Build and push the predict Docker image
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login \
          -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
        docker build . --file predict.dockerfile \
          --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}-predict:$GITHUB_SHA
        docker push \
          docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}-predict:$GITHUB_SHA
